CREATE TABLE IF NOT EXISTS CATEGORY (
	CATEGORY_ID INT IDENTITY,
	CATEGORY_RESOURCE_KEY VARCHAR(50),
	DISPLAY_ORDER INT
);

CREATE TABLE IF NOT EXISTS ALERT_TYPE (
	ALERT_TYPE_ID INT IDENTITY,
	ALERT_NAME VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS ALERT (
	ALERT_ID INT IDENTITY,
	ALERT_TYPE_ID INT,
    ALERT_RESOURCE_KEY VARCHAR(80),
	ALERT_EXTRA_LABLE_RESOURCE_KEY VARCHAR(50),
    DISPLAY_ORDER INT,
	FOREIGN KEY (ALERT_TYPE_ID) REFERENCES ALERT_TYPE
);

CREATE TABLE IF NOT EXISTS ALERT_OPTION (
	ALERT_OPTION_ID INT IDENTITY,
	ALERT_ID INT,
	ALERT_OPTION_RESOURCE_KEY VARCHAR(20),
	DISPLAY_ORDER INT,
	FOREIGN KEY (ALERT_ID) REFERENCES ALERT
);    

CREATE TABLE IF NOT EXISTS NOTIFICATION (
	NOTIFICATION_ID INT IDENTITY,
	CATEGORY_ID INT,
	NOTIFICATION_NAME_RESOURCE_KEY VARCHAR(20),
	NOTIFICATION_DESC_RESOURCE_KEY VARCHAR(80),
	DISPLAY_ORDER INT,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY
);    

CREATE TABLE IF NOT EXISTS NOTIFICATION_ALERT (
	NOTIFICATION_ALERT_ID INT IDENTITY,
	NOTIFICATION_ID INT,
	ALERT_ID INT,
	FOREIGN KEY (NOTIFICATION_ID) REFERENCES NOTIFICATION,
	FOREIGN KEY (ALERT_ID) REFERENCES ALERT
);    

CREATE TABLE IF NOT EXISTS QUESTION (
	QUESTION_ID INT IDENTITY,
	CATEGORY_ID INT,
	QUESTION_RESOURCE_KEY VARCHAR(80),
	SINGLE_SELECT INT,
	DISPLAY_ORDER INT,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY
);

CREATE TABLE IF NOT EXISTS QUESTION_OPTION (
	QUESTION_OPTION_ID INT IDENTITY,
	QUESTION_ID INT,
	QUESTION_OPTION_RESOURCE_KEY VARCHAR(80),
	DISPLAY_ORDER INT,
	FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION
);

CREATE TABLE IF NOT EXISTS USER_ANSWER (
    USER_ANSWER_ID INT IDENTITY,
    ANSWER_VALUE VARCHAR(80)
);
